name: Laravel CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install dependencies
      run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

    - name: Copy environment file
      run: cp .env.example .env

    - name: Generate application key
      run: php artisan key:generate

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install dependencies
      run: composer install --prefer-dist --no-ansi --no-interaction --no-progress

    - name: Copy environment file
      run: cp .env.example .env

    - name: Run tests with code coverage
      run: phpunit --coverage-text --coverage-html=coverage

    - name: Upload code coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage/

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to GCP VM
      run: |
        ssh -o StrictHostKeyChecking=no user@your-gcp-vm-ip "cd /path/to/your/laravel/app && git pull origin main && composer install --prefer-dist --no-ansi --no-interaction --no-progress && php artisan migrate && php artisan optimize"
